- name: cloning VM from a template
  hosts: localhost
  gather_facts: yes
  vars:
#    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: create a vm from a template
      vmware_guest_snapshot:
        hostname: "192.168.3.80"
        username: "Administrator@vsphere.local"
        password: "Kon123_5!"
        validate_certs: False
        datacenter: "KonsaltDC"
        state: remove_all
        folder: /Ansible
        name: "{{ vmname }}"
      delegate_to: localhost
